services:
  mariadb:
    image: mariadb:latest
    container_name: saboria_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${dockerport}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Sql:/docker-entrypoint-initdb.d
    networks:
      - saboria_network

volumes:
  mariadb_data:

networks:
  saboria_network: